// console.log("hello");
// alert("apan collage ");
// window.console.log("hello2");
//  console.dir(document.body);
//  console.log(document.body);
// console.dir(document.body.childNodes[1]);
// let heading =document.getElementById("heading");
// console.log(heading);
// let headings=document.getElementsByClassName("heading");
// console.dir(headings);
// console.log(headings);
// let parahs = document.getElementsBytagName("p");
// console.dir(parahs);
// let firstEL= document.querySelector("#myId");
// console.dir(firstEL);
// let allel=document.querySelectorAll(".myclass");
// console.dir(allel);
let div =document.querySelector("div");
console.dir(div);
let heading=document.querySelector("h1");